{{- if (eq .Values.ingress.className "traefik") }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirectregex
  namespace: {{ .Release.Namespace }}
spec:
  redirectRegex:
    regex: "^https://(.*)/.well-known/(card|cal)dav"
    replacement: "https://$1/remote.php/dav"
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: {{ .Release.Namespace }}
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
    customFrameOptionsValue: SAMEORIGIN
    referrerPolicy: "no-referrer"
{{- end }}
